depend: [ShinyBase]
name: ShinyChannels
main: com.hotmail.shinyclef.shinychannels.ShinyChannels
version: 3.0
commands:
    mb:
        description: Sends a message to the /mb chat channel.
        usage: /<command> [message]
    mbadd:
        description: Adds a player to the /mb chat channel.
        usage: /<command> [playername]
    mbremove:
        description: Removes a player to the /mb chat channel.
        usage: /<command> [playername]
    mblist:
        description: Displays a list of players in the /mb channel (including offline players).
        usage: /<command>
    sb:
        description: Sends a message to the /sb chat channel.
        usage: /<command> [message]
    sbadd:
        description: Adds a player to the /sb chat channel.
        usage: /<command> [playername]
    sbremove:
        description: Removes a player to the /sb chat channel.
        usage: /<command> [playername]
    sblist:
        description: Displays a list of players in the /sb channel (including offline players).
        usage: /<command>
    vip:
        description: Sends a message to the /vip chat channel.
        usage: /<command> [message]
    vipadd:
        description: Adds a player to the /vip chat channel.
        usage: /<command> [playername]
    vipremove:
        description: Removes a player to the /vip chat channel.
        usage: /<command> [playername]
    viplist:
        description: Displays a list of players in the /vip channel (including offline players).
        usage: /<command>
    t:
        description: Sends a message to normal user chat.
        usage: /<command> (chat message)
    mbon:
        description: Makes /mb your default chat channel. Use /t to talk in regular chat.
        usage: /mbon
    mboff:
        description: Makes regular chat your default chat.
        usage: /mboff